name: Docker Image CI/CD

on:
  push:
    branches: [ "firstviews" ]
  pull_request:
    branches: [ "QA", "main" ]

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract version from Git
      id: vars
      run: |
        echo "commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "version_tag=$(date +'%Y%m%d')-${{ github.run_number }}" >> $GITHUB_ENV

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME_FRONT }}
        password: ${{ secrets.DOCKER_PASSWORD_FRONT }}

    - name: Build and push Docker image
      run: |
        docker build . \
          --build-arg REACT_APP_URL_API=${{ secrets.REACT_APP_URL_API }} \
          --file Dockerfile \
          --tag ${{ secrets.DOCKER_USERNAME_FRONT }}/frontend-fashionhub:${{ env.version_tag }} \
          --tag ${{ secrets.DOCKER_USERNAME_FRONT }}/frontend-fashionhub:latest 

        docker push ${{ secrets.DOCKER_USERNAME_FRONT }}/frontend-fashionhub:${{ env.version_tag }}
        docker push ${{ secrets.DOCKER_USERNAME_FRONT }}/frontend-fashionhub:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST_FRONT }}
        username: ${{ secrets.EC2_USER_FRONT }}
        key: ${{ secrets.EC2_SSH_KEY_FRONT }}
        port: 22
        script: |
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo usermod -a -G docker ec2-user

          sudo docker pull ${{ secrets.DOCKER_USERNAME_FRONT }}/frontend-fashionhub:latest

          sudo docker ps -q --filter "name=frontend-fashionhub" | grep -q . && docker stop frontend-fashionhub && docker rm frontend-fashionhub || true
          sudo docker run -d --name frontend-fashionhub -p 80:3000 -e REACT_APP_URL_API=${{ secrets.REACT_APP_URL_API }} ${{ secrets.DOCKER_USERNAME_FRONT }}/frontend-fashionhub:latest
